FROM alpine:3.15.0

RUN apk update \
    && apk upgrade \
    && apk add ca-certificates wget coreutils patch grep \
    && update-ca-certificates \
    && apk add --virtual build-deps \
        make \
        gcc \
        make \
        g++ \
        zlib-dev \
        musl-dev \
        pcre-dev \
        openssl-dev \
        zlib-dev \
        ncurses-dev \
        readline-dev \
        curl \
        perl \
        libffi-dev \
        git \
        unzip \
        tar \
        openssh \
        m4 \
        xz \
        gnupg \
        openssl \
        musl \
        linux-headers \
        bsd-compat-headers \
        bash \
        go \
        cmake \
    && curl -sSL https://github.com/mikefarah/yq/releases/download/1.15.0/yq_linux_amd64 -o /usr/local/bin/yaml \
    && chmod +x /usr/local/bin/yaml
