---
name: Build and Optionally Release

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Setup buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Only
      uses: docker/bake-action@v1
      with:
        files: |
          ./docker-bake.hcl
    - name: Release
      id: release
      uses: ahmadnassri/action-semantic-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to DockerHub
      if: steps['release']['outputs']['published'] == 'true'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push
      if: steps['release']['outputs']['published'] == 'true'
      uses: docker/bake-action@v1
      env:
        TAG: ${{steps.release.outputs.release-version}}
      with:
        push: 'true'
